### PR TITLE
Add support for CSS

### PR DESCRIPTION
**Pull request by cben**
- Using version.js to load CSS allows the CSS to also be controlled by url param.  This is especially good to avoid version mismatches when also using JS from same library, see below.
- First, I was happily surprised that I can load version.js many times with different options and it Just Worked, so I also documented that :-)
- Also a small unrelated test fix & improvement.

Tests pass, locally and on Sauce Labs.

Use example:
https://github.com/cben/CodeMirror-MathJax/compare/a43ceb0e90e78099cb76a867d885839ea463387c...146765f9b6d6424902cded88010e842348cc819f
(live demo: http://cben.github.io/CodeMirror-MathJax/demo.html)
I'm using several .js and a .css from CodeMirror.  This css doesn't change much so always using the latest worked in practice, but obviously loading the matching version is cleaner.

I tested that writing a `<link>` to css works both inside `<head>` and `<body>` (the latter is likely if calling `version.load({type: 'css', ...})` from a script inside the body):
http://codepen.io/cben/pen/PPOdzY => http://app.crossbrowsertesting.com/public/i866dfd0fa0b9da1/screenshots/z932042ae88a74c37f7a
(lower half black means the css loaded from body).
Turns out Codepen doesn't support any way to load css from head, it puts ALL scripts and links into body, which gives me confidence it's not a problem.
I also put one of the css loads in I added to runner.tmpl into the body, and it worked on the 12 saucelabs platforms.
http://stackoverflow.com/a/30308194/239657 explains that technically `<link rel=stylesheet>` in body doesn't validate but can be made valid by adding `property="stylesheet"` — I don't think we care in dynamically added element as long as browsers understand it's css, but it's trivial to add if you want.

I also added a `suffix`/`data-suffix` option.  Given `data-file="foo"` I needed a way to load `.../foo.css` instead of  `.../foo.js`, so I added `{{SUFFIX}}` to the template, by default depending on `type`, and it made sense to expose it.
But I also had an unrelated motivation to add it, which is also why I called it "suffix" and not "extension":
Some libraries such as MathJax expect parameters passed via `?...` tacked onto the URL.  Naively writing `data-file="MathJax.js?...` is wrong because `.js` is added at the end, so I had to override the full `data-url`; with suffix exposed I can still use the standard cdnjs template.  See example in the "use example" github diff link above.
[In retrospect it would have been cleaner if `file` included the extension when given.  Could still default to lib+'.js' — or now sometimes lib+'.css' — when omitted.  But can't change that without breaking compatibility.]

### CODE REVIEW

**Comment by cben** [comment]
Oops turns out I based the changes to a half-year-old version.js.
I'll rebase and re-test tomorrow.

**Comment by cben** [comment]
Rebased on head, ready for you to take a look.

**Comment by cben** [comment]
@jstayton ping, if this project is not completely abandoned, please review.

**Comment by jstayton** [comment]
@cben I'm very sorry for never responding to you here. As my silence likely hinted, I stopped maintaining this project long ago. I'm now officially deprecating it to make that clear.

If you'd like to continue supporting a forked version, please reach out on Twitter ([@kidjustino](https://twitter.com/kidjustino)) to have it listed in the README.

**Pull request closed without merging**
